"""empty message

Revision ID: e2435cc17f94
Revises: 0f9decc54f0f
Create Date: 2025-06-05 12:40:57.057865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2435cc17f94'
down_revision = '0f9decc54f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reviews_course_user', ['course_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reviews_course_user', type_='unique')

    # ### end Alembic commands ###
